[package]
name = "dbus-bounce"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "2.0.0-beta.7"
async-std = {version = "1", features = ["attributes"]}
